development:
      host: 127.0.0.1
      adapter: mysql
      database: alfurqan
      port: 3306
      username: root
      password: root

test: &test
      host: localhost
      adapter: mysql
      database: fedena_two_new
      port: 3306
      username: root
      password: foradian

production:
      host: 127.0.0.1
      adapter: mysql
      database: alfurqan
      port: 3306
      username: root
      password: root
cucumber:
  <<: *test
